src/main/java/io/jenkins/plugins/orka/OrkaCloud.java
src/main/java/io/jenkins/plugins/orka/OrkaProvisionedAgent.java
src/main/java/io/jenkins/plugins/orka/WaitSSHLauncher.java

This provides better user experience as users see the VM right away.

Wait for SSH after VM is deployed and visible

---

src/main/java/io/jenkins/plugins/orka/AgentTemplate.java
src/main/java/io/jenkins/plugins/orka/OrkaAgent.java
src/main/java/io/jenkins/plugins/orka/helpers/OrkaInfoHelper.java
src/main/resources/io/jenkins/plugins/orka/AgentTemplate/config.jelly
src/main/resources/io/jenkins/plugins/orka/OrkaAgent/configure-entries.jelly

We were not showing what numCPUs value was selected and saved and were always showing 3.

Correctly show the selected numCPUs value

---

src/main/java/io/jenkins/plugins/orka/OrkaCloud.java

Jenkins will add them automatically once their initialization is done, no need to do this manually

Do not add cloud agents manually

---

src/main/java/io/jenkins/plugins/orka/OrkaCloud.java

We can receive null as label during provision. This is a valid value and we should handle it correctly.

Fix provision for "any" agents

---

src/main/java/io/jenkins/plugins/orka/OrkaCloud.java
src/main/java/io/jenkins/plugins/orka/helpers/CapacityHandler.java
src/main/resources/io/jenkins/plugins/orka/OrkaCloud/config.jelly
src/main/resources/io/jenkins/plugins/orka/OrkaCloud/help-instanceCapSetting.html
src/test/java/io/jenkins/plugins/orka/GetTemplateTest.java
src/test/java/io/jenkins/plugins/orka/helpers/CapacityHandlerTest.java

This allows customers to set agents cap per cloud.

ORKA-236 Introduce max Jenkins agents limit

---

README.md
src/main/java/io/jenkins/plugins/orka/OrkaCloud.java
src/main/java/io/jenkins/plugins/orka/client/OrkaClient.java
src/main/java/io/jenkins/plugins/orka/helpers/OrkaClientProxy.java
src/main/java/io/jenkins/plugins/orka/helpers/OrkaClientProxyFactory.java
src/main/resources/io/jenkins/plugins/orka/OrkaCloud/config.jelly
src/test/java/io/jenkins/plugins/orka/GetTemplateTest.java

Add option to configure deployment timeout for ephemeral agents. Defaults to 5 min. (=300seconds)

(feat) Add config for ephemeral agents deployment timeout

---

src/main/java/io/jenkins/plugins/orka/AgentTemplate.java

This will provide us with more logging information if something goes wrong

Log if configuration creation has failed

---

pom.xml

Bump deps versions as well as the old ones are no longer supported

Bump supported Jenkins version to 2.190.1

---

src/main/java/io/jenkins/plugins/orka/AgentTemplate.java
src/main/java/io/jenkins/plugins/orka/OrkaAgent.java
src/main/java/io/jenkins/plugins/orka/OrkaCloud.java
src/main/java/io/jenkins/plugins/orka/OrkaComputerLauncher.java
src/main/java/io/jenkins/plugins/orka/client/OrkaClient.java
src/main/java/io/jenkins/plugins/orka/helpers/FormValidator.java
src/main/java/io/jenkins/plugins/orka/helpers/OrkaClientProxy.java
src/main/java/io/jenkins/plugins/orka/helpers/OrkaClientProxyFactory.java
src/main/java/io/jenkins/plugins/orka/helpers/OrkaInfoHelper.java
src/main/resources/io/jenkins/plugins/orka/OrkaAgent/configure-entries.jelly
src/main/resources/io/jenkins/plugins/orka/OrkaAgent/help-useJenkinsProxySettings.html
src/main/resources/io/jenkins/plugins/orka/OrkaCloud/config.jelly
src/main/resources/io/jenkins/plugins/orka/OrkaCloud/help-useJenkinsProxySettings.html
src/test/java/io/jenkins/plugins/orka/ConfigNameCheckTest.java
src/test/java/io/jenkins/plugins/orka/GetTemplateTest.java
src/test/java/io/jenkins/plugins/orka/ImageItemsFillTest.java
src/test/java/io/jenkins/plugins/orka/NodeItemsFillTest.java
src/test/java/io/jenkins/plugins/orka/NodeNameCheckTest.java
src/test/java/io/jenkins/plugins/orka/NodeResourcesCheckTest.java
src/test/java/io/jenkins/plugins/orka/OrkaAgentDescriptorImplTest.java
src/test/java/io/jenkins/plugins/orka/VMItemsFillTest.java

Allow users to choose whether the plugin should respect the Jenkins http proxy settings for Orka API requests or not

Use Jenkins HTTP settings in the plugin

---

pom.xml
src/main/java/io/jenkins/plugins/orka/helpers/SSHUtil.java

It is possible that the initial connection can fail.
Retry to make sure we are connected.

Retry SSH connections during AES verifications

---

src/main/java/io/jenkins/plugins/orka/AgentTemplate.java
src/main/java/io/jenkins/plugins/orka/OrkaAgent.java
src/main/java/io/jenkins/plugins/orka/OrkaCloud.java
src/main/java/io/jenkins/plugins/orka/OrkaComputerLauncher.java
src/main/java/io/jenkins/plugins/orka/client/OrkaClient.java
src/main/java/io/jenkins/plugins/orka/client/SSLHelper.java
src/main/java/io/jenkins/plugins/orka/helpers/FormValidator.java
src/main/java/io/jenkins/plugins/orka/helpers/OrkaClientProxy.java
src/main/java/io/jenkins/plugins/orka/helpers/OrkaClientProxyFactory.java
src/main/java/io/jenkins/plugins/orka/helpers/OrkaInfoHelper.java
src/main/resources/io/jenkins/plugins/orka/OrkaAgent/configure-entries.jelly
src/main/resources/io/jenkins/plugins/orka/OrkaCloud/config.jelly
src/test/java/io/jenkins/plugins/orka/ConfigNameCheckTest.java
src/test/java/io/jenkins/plugins/orka/ImageItemsFillTest.java
src/test/java/io/jenkins/plugins/orka/NodeItemsFillTest.java
src/test/java/io/jenkins/plugins/orka/NodeNameCheckTest.java
src/test/java/io/jenkins/plugins/orka/NodeResourcesCheckTest.java
src/test/java/io/jenkins/plugins/orka/OrkaAgentDescriptorImplTest.java
src/test/java/io/jenkins/plugins/orka/VMItemsFillTest.java

Users should be able to ignore SSL errors if they want to.

Add an option to allow ignoring SSL errors

---

README.md
integration-tests/jenkins-setup/init-cloud.groovy
src/main/java/io/jenkins/plugins/orka/OrkaCloud.java
src/main/java/io/jenkins/plugins/orka/client/OrkaClient.java
src/main/resources/io/jenkins/plugins/orka/OrkaCloud/help-timeout.html

Increase the default http timeout from 5mins to 10mins

---

src/main/java/io/jenkins/plugins/orka/AgentTemplate.java
src/main/java/io/jenkins/plugins/orka/Constants.java
src/main/java/io/jenkins/plugins/orka/OrkaAgent.java
src/main/java/io/jenkins/plugins/orka/OrkaCloud.java
src/main/java/io/jenkins/plugins/orka/OrkaComputerLauncher.java
src/main/java/io/jenkins/plugins/orka/client/ConfigurationRequest.java
src/main/java/io/jenkins/plugins/orka/client/DeploymentRequest.java
src/main/java/io/jenkins/plugins/orka/client/OrkaClient.java
src/main/java/io/jenkins/plugins/orka/helpers/OrkaClientProxy.java
src/main/java/io/jenkins/plugins/orka/helpers/OrkaClientProxyFactory.java
src/main/java/io/jenkins/plugins/orka/helpers/OrkaInfoHelper.java
src/main/resources/io/jenkins/plugins/orka/AgentTemplate/config.jelly
src/main/resources/io/jenkins/plugins/orka/AgentTemplate/help-scheduler.html
src/main/resources/io/jenkins/plugins/orka/OrkaAgent/configure-entries.jelly
src/main/resources/io/jenkins/plugins/orka/OrkaAgent/help-scheduler.html
src/test/java/io/jenkins/plugins/orka/AgentTemplateTest.java
src/test/java/io/jenkins/plugins/orka/client/OrkaClientTest.java

Adds the ability to choose the desired scheduler `default` or `most-allocated` when creating a VM config.

OK-322 - Add Scheduler Choice for VM Config

---

src/main/java/io/jenkins/plugins/orka/AgentTemplate.java
src/main/java/io/jenkins/plugins/orka/OrkaAgent.java
src/main/java/io/jenkins/plugins/orka/OrkaCloud.java
src/main/java/io/jenkins/plugins/orka/OrkaComputerLauncher.java
src/main/java/io/jenkins/plugins/orka/client/ConfigurationRequest.java
src/main/java/io/jenkins/plugins/orka/client/OrkaClient.java
src/main/java/io/jenkins/plugins/orka/client/OrkaVM.java
src/main/java/io/jenkins/plugins/orka/client/OrkaVMConfig.java
src/main/java/io/jenkins/plugins/orka/helpers/FormValidator.java
src/main/java/io/jenkins/plugins/orka/helpers/OrkaClientProxy.java
src/main/resources/io/jenkins/plugins/orka/AgentTemplate/config.jelly
src/main/resources/io/jenkins/plugins/orka/AgentTemplate/help-memory.html
src/main/resources/io/jenkins/plugins/orka/OrkaAgent/configure-entries.jelly
src/main/resources/io/jenkins/plugins/orka/OrkaAgent/help-memory.html
src/test/java/io/jenkins/plugins/orka/client/OrkaClientTest.java

Adds memory to vm configs. 
JIRA: https://macstadium.atlassian.net/jira/software/c/projects/OK/boards/84?modal=detail&selectedIssue=OK-552
Adds `memory` to:
- Orka Computer
- Orka Agent Template
- OrkaVM
- OrkaVMConfig
- OrkaClient
- OrkaClientProxy
- OrkaClientTest

OK-552 - Add Memory configuration

---

src/main/java/io/jenkins/plugins/orka/OrkaComputerLauncher.java
src/main/java/io/jenkins/plugins/orka/WaitSSHLauncher.java
src/main/java/io/jenkins/plugins/orka/helpers/SSHUtil.java

Previously, it was possible to get stuck when SSH was not enabled.

Add a timeout when checking for SSH connection

---

src/main/java/io/jenkins/plugins/orka/NoDelayProvisionerStrategy.java
src/main/java/io/jenkins/plugins/orka/OrkaCloud.java
src/main/resources/io/jenkins/plugins/orka/OrkaCloud/config.jelly
src/main/resources/io/jenkins/plugins/orka/OrkaCloud/help-noDelayProvisioning.html

Allow users to bypass the standard Jenkins algorithm and provision Orka agents as soon as they are needed.

Introduce NoDelayProvisionerStrategy

---

src/main/java/io/jenkins/plugins/orka/OrkaVersionChecker.java
src/main/java/io/jenkins/plugins/orka/OrkaVersionMonitor.java
src/main/java/io/jenkins/plugins/orka/client/OrkaClientV2.java
src/main/java/io/jenkins/plugins/orka/helpers/OrkaClientProxyFactory.java
src/test/java/io/jenkins/plugins/orka/UtilsTest.java

Run the check on Jenkins init. Otherwise, we might wait for an hour until we get the correct version.
Ensure we pass the server version to the OrkaClientProxy.

Server check improvements

---

src/main/java/io/jenkins/plugins/orka/AESVerificationStrategy.java
src/main/java/io/jenkins/plugins/orka/AgentTemplate.java
src/main/java/io/jenkins/plugins/orka/OrkaAgent.java
src/main/java/io/jenkins/plugins/orka/OrkaCloud.java
src/main/java/io/jenkins/plugins/orka/OrkaProvisionedAgent.java
src/main/resources/io/jenkins/plugins/orka/AgentTemplate/help-verificationStrategy.html
src/main/resources/io/jenkins/plugins/orka/OrkaProvisionedAgent/help-verificationStrategy.html

Refactorings

---

src/main/java/io/jenkins/plugins/orka/client/SSLHelper.java

Use a newer protocol for SSL context

Update the SSL Context protocol to TLSv1.3

---

README.md
development/RELEASING.md
development/TIPS.md
development/TROUBLESHOOTING.md

This fix adds a link to service account documentation, notes that display settings are under the 'Advanced' section and their defaults, and generally cleans up grammar in the troubleshooting, releasing, and tips documentation.
There is an internal JIRA ticket to track/reference this work available if needed.
- [ x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ x] Ensure that the pull request title represents the desired changelog entry
- [ x] Please describe what you did
- [ x] Link to relevant issues in GitHub or Jira

docs: update README
