- src/main/java/io/jenkins/plugins/orka/AgentTemplate.java
- src/main/java/io/jenkins/plugins/orka/OrkaAgent.java
- src/main/java/io/jenkins/plugins/orka/OrkaComputerLauncher.java
- src/main/resources/io/jenkins/plugins/orka/AgentTemplate/config.jelly
- src/main/resources/io/jenkins/plugins/orka/OrkaAgent/configure-entries.jelly
- src/test/java/io/jenkins/plugins/orka/AgentTemplateTest.java
- src/test/java/io/jenkins/plugins/orka/GetTemplateTest.java
The values doesn't make a difference, so we can reuse the name of the config.
Remove the property as it can only confuse users
> Hide "image" property for new configs

- src/main/java/io/jenkins/plugins/orka/AddressMapper.java
- src/main/java/io/jenkins/plugins/orka/AgentTemplate.java
- src/main/java/io/jenkins/plugins/orka/OrkaAgent.java
- src/main/java/io/jenkins/plugins/orka/OrkaCloud.java
- src/main/java/io/jenkins/plugins/orka/OrkaComputerLauncher.java
- src/main/resources/io/jenkins/plugins/orka/AddressMapper/config.jelly
- src/main/resources/io/jenkins/plugins/orka/AddressMapper/help-defaultHost.html
- src/main/resources/io/jenkins/plugins/orka/AddressMapper/help-redirectHost.html
- src/main/resources/io/jenkins/plugins/orka/OrkaAgent/configure-entries.jelly
- src/main/resources/io/jenkins/plugins/orka/OrkaAgent/help-redirectHost.html
- src/main/resources/io/jenkins/plugins/orka/OrkaCloud/config.jelly
- src/test/java/io/jenkins/plugins/orka/AgentTemplateTest.java
- src/test/java/io/jenkins/plugins/orka/GetTemplateTest.java
Node host addresses may be in conflict with local networks.
Allow users to overwrite addresses and use public ones, which will be used to connect to Orka VMs.1
> Allow node host address to be overwritten

- src/main/java/io/jenkins/plugins/orka/AgentTemplate.java
- src/main/java/io/jenkins/plugins/orka/OrkaCloud.java
When creating ephemeral agents make sure the deployment is succesfull.
If there any errors display them and return an empty result. This will force Jenkins to retry.
> Hanlde failed deployments correctly

- src/main/java/io/jenkins/plugins/orka/client/OrkaClient.java
If the API is under heavy load (deployment of 10+ VMs) some requests may fail leaving orpahned VMs.
Increase the timeout to mitigate that.
> Increase Orka request timeout to 5 min

- src/main/java/io/jenkins/plugins/orka/helpers/CapacityHandler.java
- src/test/java/io/jenkins/plugins/orka/helpers/CapacityHandlerTest.java
Pressing the remove instance button more than once leads to negative numbers. Make sure this does not happen
> Make sure running instances are always a positive number

- src/main/java/io/jenkins/plugins/orka/OrkaCloud.java
- src/main/resources/io/jenkins/plugins/orka/AgentTemplate/config.jelly
- src/main/resources/io/jenkins/plugins/orka/OrkaAgent/configure-entries.jelly
- src/main/resources/io/jenkins/plugins/orka/OrkaComputer/configure.jelly
- src/main/resources/io/jenkins/plugins/orka/OrkaProvisionedAgent/configure-entries.jelly
We were not showing the correct selected item for the node mode.
The issue was caused by not using the correct instance object to find out which is the selected item
> Fix node mode selection in the UI

- checkstyle.xml
- src/main/java/io/jenkins/plugins/orka/AESVerificationStrategy.java
- src/main/java/io/jenkins/plugins/orka/AgentTemplate.java
- src/main/java/io/jenkins/plugins/orka/DefaultVerificationStrategy.java
- src/main/java/io/jenkins/plugins/orka/OrkaProvisionedAgent.java
- src/main/java/io/jenkins/plugins/orka/OrkaVerificationStrategy.java
- src/main/java/io/jenkins/plugins/orka/WaitSSHLauncher.java
- src/main/java/io/jenkins/plugins/orka/helpers/AESDecryptor.java
- src/main/java/io/jenkins/plugins/orka/helpers/CredentialsHelper.java
- src/main/java/io/jenkins/plugins/orka/helpers/CryptoUtil.java
- src/main/java/io/jenkins/plugins/orka/helpers/OrkaVerificationStrategyProvider.java
- src/main/java/io/jenkins/plugins/orka/helpers/SSHUtil.java
- src/main/resources/io/jenkins/plugins/orka/AESVerificationStrategy/config.jelly
- src/main/resources/io/jenkins/plugins/orka/AESVerificationStrategy/help-encryptionScript.html
- src/main/resources/io/jenkins/plugins/orka/AgentTemplate/config.jelly
- src/main/resources/io/jenkins/plugins/orka/AgentTemplate/help-verificationStrategy.html
- src/main/resources/io/jenkins/plugins/orka/OrkaProvisionedAgent/configure-entries.jelly
- src/main/resources/io/jenkins/plugins/orka/OrkaProvisionedAgent/help-verificationStrategy.html
- src/test/java/io/jenkins/plugins/orka/AgentTemplateTest.java
- src/test/java/io/jenkins/plugins/orka/GetTemplateTest.java
- src/test/java/io/jenkins/plugins/orka/helpers/AESDecryptorTest.java
- src/test/java/io/jenkins/plugins/orka/helpers/CapacityHandlerTest.java
They allow verifying a VM prior to making it a Jenkins agent.
This way if a VM is not trusted we can delete it and create a new one.
Current strategies:
* Default - rely on VPN and SSH security
* AES - allow users to create a custom AES verification handshake
In addition, allow extensibility of the verification, meaning users can implement their own and plug them into the plugin.
> Introduce agent verification strategies

- src/main/java/io/jenkins/plugins/orka/AgentTemplate.java
- src/main/java/io/jenkins/plugins/orka/OrkaComputerLauncher.java
- src/main/java/io/jenkins/plugins/orka/client/OrkaClient.java
- src/main/java/io/jenkins/plugins/orka/client/ResponseBase.java
- src/main/java/io/jenkins/plugins/orka/helpers/Utils.java
We were using the response body to check if there were any errors.
This could lead to unexpected behavior when the body does not contain an error.
Instead check the status code of the response.
> Use the HTTP status code to check for errors

- pom.xml
- src/main/java/io/jenkins/plugins/orka/client/OrkaClient.java
Okhttp seems to have issues with HTTP 2 and Java 8. Requests fail with various reasons.
Up until OpenJDK 8_242 HTTP 1.1 was used for both http and https requests.
However, OpenJDK 8_252 contains a backport from Java 9, which breaks OkHttp logic.
Two issues appear:
1. The library starts to think we are running under Java 9 instead of Java 8
2. It starts preferring HTTP 2 over HTTP 1
Updating to OkHttp 4.8 fixes the former issue. However, HTTP2 continues to be the preffered protocol.
To fix that issue allow HTTP 1.1 only.
> Always use HTTP 1.1 for Orka connections

- src/main/java/io/jenkins/plugins/orka/client/OrkaClient.java
- src/main/java/io/jenkins/plugins/orka/client/TokenStatusResponse.java
- src/main/java/io/jenkins/plugins/orka/helpers/FormValidator.java
- src/main/java/io/jenkins/plugins/orka/helpers/OrkaClientProxy.java
We were listing all available nodes during test connection
In large clusters this can take some time (10 or more seconds).
Change the check with token status check.
> Optimize test connection

- src/main/java/io/jenkins/plugins/orka/AgentTemplate.java
- src/main/java/io/jenkins/plugins/orka/OrkaProvisionedAgent.java
If agent creation fails, we did not remove any VMs which left to orphaned VMs.
In addition, make sure we do not pass unexpected values for retentionStrategy and nodeProperties. Unexpected values can be set when configuring the Jenkins plugin with code.
> Delete VMs if agent creation fails

- src/main/java/io/jenkins/plugins/orka/AgentTemplate.java
- src/main/java/io/jenkins/plugins/orka/OrkaProvisionedAgent.java
- src/main/resources/io/jenkins/plugins/orka/AgentTemplate/config.jelly
- src/test/java/io/jenkins/plugins/orka/helpers/CapacityHandlerTest.java
We had several issues:
1. Node Properties were not persisted in the Cloud configuration
2. Node Properties were limited to "Tools Location" only. Other properties like "Environment Variables" were not available
Causes:
1. We were returning the wrong type
2. We were using the wrong descriptor for node properties. It was AgentTemplate, but it should be OrkaProvisionedAgent as we are assigning the properties to instances of this type
> Fix the way we handle node properties

- src/main/java/io/jenkins/plugins/orka/IdleTimeCloudRetentionStrategy.java
- src/main/java/io/jenkins/plugins/orka/RunOnceCloudRetentionStrategy.java
The retention strategies could not be set via the Configuration as Code plugin (casc).
The issue is that we do not expose them to Jenkins via an Extension and casc cannot find them.
The fix - expose the retention strategy descriptors
> Add support for configuration as code

- src/main/java/io/jenkins/plugins/orka/OrkaProvisionedAgent.java
We were using the wrong type for node properties and changing an existing agent configuration was impossible.
> Fix cloud agent recondiguration

- .github/workflows/release-plugin.yml
- pom.xml
Update the scm connections to use https instead of the git protocol.
This allows us to use the built-in GITHUB_TOKEN in the workflow to update the repo
> Introduce release workflow for the plugin

- integration-tests/jenkins-setup/init-cloud.groovy
- src/main/java/io/jenkins/plugins/orka/AgentTemplate.java
- src/main/java/io/jenkins/plugins/orka/OrkaProvisionedAgent.java
- src/main/resources/io/jenkins/plugins/orka/AgentTemplate/config.jelly
- src/main/resources/io/jenkins/plugins/orka/AgentTemplate/help-namePrefix.html
- src/main/resources/io/jenkins/plugins/orka/OrkaProvisionedAgent/configure-entries.jelly
- src/test/java/io/jenkins/plugins/orka/AgentTemplateTest.java
- src/test/java/io/jenkins/plugins/orka/GetTemplateTest.java
- src/test/java/io/jenkins/plugins/orka/helpers/CapacityHandlerTest.java
Currently the agents are named on the ID of the VM that stays behind them. With this feature, the user is allowed to specify a prefix in the agents config. The prefix then is added in front of the VM ID and the agent name looks like `prefix_vmid`. This gives the user a better way to distinguish between agents.
> (feat) Allow the user to add a prefix to the cloud agent's name

- src/main/java/io/jenkins/plugins/orka/AgentTemplate.java
- src/main/java/io/jenkins/plugins/orka/OrkaCloud.java
- src/main/java/io/jenkins/plugins/orka/client/OrkaClient.java
- src/main/java/io/jenkins/plugins/orka/client/OrkaVMConfig.java
- src/main/java/io/jenkins/plugins/orka/client/VMConfigResponse.java
- src/main/java/io/jenkins/plugins/orka/helpers/OrkaClientProxy.java
It is cleaner to use the config endpoint to check for existing configs.
In addition, the vms endpoint may not return a config if it has failed
to deploy, resulting in errors.
> Use the config endpoint to check for existing configs

- src/main/resources/io/jenkins/plugins/orka/AddressMapper/config.jelly
- src/main/resources/io/jenkins/plugins/orka/AgentTemplate/config.jelly
- src/main/resources/lib/orka/blockWrapper.jelly
Jenkins are moving away from table elements in favor to div.
This is breaking the current layout in the plugin cloud configuration.
Introduce a blockWrapper that is also backwards compatible and changes between table and div depending on the version.
> Make sure we follow Jenkins new layout

- src/main/resources/io/jenkins/plugins/orka/OrkaAgent/configure-entries.jelly
- src/main/resources/io/jenkins/plugins/orka/OrkaComputer/configure.jelly
We need to hide some additional fields otherwise they are incorrectly passed to the ctor.
This results in no matching ctor found and not permanent agents can be created.
> Fix creation of permanent agents

- src/main/java/io/jenkins/plugins/orka/AgentTemplate.java
- src/main/java/io/jenkins/plugins/orka/OrkaAgent.java
- src/main/java/io/jenkins/plugins/orka/OrkaComputerLauncher.java
- src/main/java/io/jenkins/plugins/orka/OrkaProvisionedAgent.java
- src/main/java/io/jenkins/plugins/orka/WaitSSHLauncher.java
- src/main/resources/io/jenkins/plugins/orka/AgentTemplate/config.jelly
- src/main/resources/io/jenkins/plugins/orka/OrkaAgent/configure-entries.jelly
- src/main/resources/io/jenkins/plugins/orka/OrkaComputer/configure.jelly
- src/main/resources/io/jenkins/plugins/orka/OrkaProvisionedAgent/configure-entries.jelly
This PR adds an ability for the users to provide JVM options for both ephemeral and permanent Orka Jenkins agents.
> ORKA-857 Allow users to provide JVM options to the Orka agents

- src/main/java/io/jenkins/plugins/orka/OrkaCloud.java
- src/main/resources/io/jenkins/plugins/orka/OrkaCloud/config.jelly
- src/main/resources/io/jenkins/plugins/orka/OrkaCloud/help-deletionTimeout.html
- src/main/resources/io/jenkins/plugins/orka/OrkaCloud/help-httpTimeout.html
Introduce configuration option to set http timeout for all requests made to the Orka API except deploy - it has it's own configuration option for deploy timeout.
> OK-521  - Introduce configurable http timeout for non-deployment operations

- src/main/java/io/jenkins/plugins/orka/helpers/AESDecryptor.java
JAXB has been removed in Java 9+, so use the Java Platform's built-in class instead. CC @DanMHammer
> Use built-in Base64 decoder

- src/main/java/io/jenkins/plugins/orka/client/JsonHelper.java
- src/main/java/io/jenkins/plugins/orka/client/OrkaClient.java
In case we get a non json response we cannot parse it and we never log what it was.
We now log it so we can troubleshoot what is going on.
> Add more log when failing to parse a json response

- src/main/java/io/jenkins/plugins/orka/OrkaVersionMonitor.java
- src/main/java/io/jenkins/plugins/orka/client/HealthCheckResponse.java
- src/main/java/io/jenkins/plugins/orka/client/OrkaClient.java
- src/main/java/io/jenkins/plugins/orka/client/OrkaClientV2.java
- src/main/java/io/jenkins/plugins/orka/helpers/FormValidator.java
- src/main/java/io/jenkins/plugins/orka/helpers/OrkaClientProxy.java
- src/main/java/io/jenkins/plugins/orka/helpers/OrkaClientProxyFactory.java
- src/main/java/io/jenkins/plugins/orka/helpers/Utils.java
- src/test/java/io/jenkins/plugins/orka/UtilsTest.java
- src/test/java/io/jenkins/plugins/orka/client/OrkaClientTest.java
Previously, the server was storing tons of tokens in a DB and we needed to revoke them to prevent DB pollution.
Now, there is a single token per user, so we no longer need to revoke them.
In addition, detect the server version and choose our approach base on that.
> Take advantage of Orka API new token algorithm

- src/main/java/io/jenkins/plugins/orka/client/OrkaClient.java
- src/main/java/io/jenkins/plugins/orka/helpers/OrkaClientProxy.java
Whenever we perform a health check, we are recreating an `OrkaClient`. If we're on Orka versions lower than 2.1.1, or it's the first time we are performing the check after Jenkins restart, this forces the reinitialization of the authentication token. This means that any active tokens are revoked and therefore the users are logged out from all of their other systems (such as CLI, web UI).
Because the health check doesn't actually need an authentication token, just skip generating one for this case (and thereby skip revoking it when the client is closed shortly).
> Fix overzealous auth token revocation

- src/main/java/io/jenkins/plugins/orka/AgentTemplate.java
- src/main/java/io/jenkins/plugins/orka/OrkaAgent.java
- src/main/java/io/jenkins/plugins/orka/OrkaCloud.java
- src/main/java/io/jenkins/plugins/orka/OrkaComputerLauncher.java
- src/main/java/io/jenkins/plugins/orka/client/ConfigurationRequest.java
- src/main/java/io/jenkins/plugins/orka/client/OrkaClient.java
- src/main/java/io/jenkins/plugins/orka/helpers/OrkaClientProxy.java
- src/main/resources/io/jenkins/plugins/orka/AgentTemplate/config.jelly
- src/main/resources/io/jenkins/plugins/orka/OrkaAgent/configure-entries.jelly
- src/test/java/io/jenkins/plugins/orka/client/OrkaClientTest.java
Net Boost is required for newer Ventura VMs, but may have to be forcibly disabled for older OS images. Expose a checkbox for controlling this behaviour.
> Add a configuration checkbox for controlling Net Boost

- src/main/java/io/jenkins/plugins/orka/client/ConfigurationRequest.java
- src/main/java/io/jenkins/plugins/orka/helpers/FormValidator.java
Adds the ability to use floating point values for memory on new VM configs.
Validation - Config created through Jenkins with 5.45 G:
Macstadium JIRA Issue: https://macstadium.atlassian.net/browse/OK-1116?atlOrigin=eyJpIjoiNTFiYTdkODRmYmYyNDgzYmEzOGM0NjNiNWY0NzI4NjIiLCJwIjoiaiJ9
> OK-1116 - Allow floating point memory on vm configs

- src/main/java/io/jenkins/plugins/orka/CloudSaveListener.java
- src/main/java/io/jenkins/plugins/orka/helpers/OrkaClientProxy.java
During a fresh plugin install there is no cloud, so our logic does not set a server version. This results in a token being revoke on each request once a cloud has been added.
To fix that:
1. Change the default behavior not to revoke tokens if there is no version
2. Listen for Jenkins config changes and update the version. This would handle the addition of a new cluster.
> Fix incorrectly revoking tokens on fresh plugin install

- src/main/java/io/jenkins/plugins/orka/OrkaComputerLauncher.java
- src/main/java/io/jenkins/plugins/orka/OrkaVersionChecker.java
Currently, the logic for token revocation was only working for ephemeral agents. Update it to work for permanent as well
> Handle token revocation with permanent agents

- pom.xml
- src/main/java/io/jenkins/plugins/orka/helpers/CredentialsHelper.java
- src/main/java/io/jenkins/plugins/orka/helpers/OrkaClientFactory.java
- src/test/java/io/jenkins/plugins/orka/OrkaAgentDescriptorImplTest.java
Currently, we only allow Username/Password credentials. However, this is counter-intuitive as we want users to only store tokens. Allow SecretText as well, which is intended for tokens
1. Install the plugin
2. Create a new Orka Cloud
3. Add the Orka token as a SecretText
4. Run "Verify Connection"
Should be successful
> OK-2917 Allow using SecretText for storing tokens

- src/main/java/io/jenkins/plugins/orka/client/DeploymentRequest.java
Orka server has a default timeout of 10 minutes. We can increase this timeout. However, there isn't need for that in the plugin. We already have a request timeout for deployment, so we keep using it. Make sure to increase the server timeout to a day, so it is always greater than the request timeout. Essentially we make sure than the server timeout never kicks in
> OK-2934 Fix server timeout when deploying VMs

- development/DEVELOPING.md
- pom.xml
- src/main/java/io/jenkins/plugins/orka/OrkaAgent.java
- src/main/java/io/jenkins/plugins/orka/OrkaCloud.java
- src/main/java/io/jenkins/plugins/orka/OrkaComputerLauncher.java
- src/main/java/io/jenkins/plugins/orka/client/DeploymentRequest.java
- src/main/java/io/jenkins/plugins/orka/client/OrkaClient.java
- src/main/resources/io/jenkins/plugins/orka/OrkaAgent/configure-entries.jelly
- src/test/java/io/jenkins/plugins/orka/client/OrkaClientTest.java
Updated Jelly files to add widget for users to create custom port mapping when creating VMs. Updated backend Java code to process the port mapping inputs and pass the ports the method that creates the VM.
This change was tested inside of Jenkins. A permanent agent was created with three custom port mappings.  The VM was created correctly with the custom ports.
> Ok 3299  Allow Port Mapping for permanent agents

- src/main/java/io/jenkins/plugins/orka/AgentTemplate.java
- src/main/java/io/jenkins/plugins/orka/OrkaCloud.java
- src/main/java/io/jenkins/plugins/orka/client/DeploymentRequest.java
- src/main/java/io/jenkins/plugins/orka/client/OrkaClient.java
- src/main/java/io/jenkins/plugins/orka/helpers/VMNameGenerator.java
- src/test/java/io/jenkins/plugins/orka/AgentTemplateTest.java
- src/test/java/io/jenkins/plugins/orka/helpers/VMNameGeneratorTest.java
The plugin now creates the VM names instead of relying on the K8s API to generate those.
This way the plugin knows about the VM if the deployment fails.
And it is able to delete the VM so no orphaned VMs are left.
Build the plugin locally (Ensure your Java home points to Java 8): `mvn clean && mvn package`
Create an image with latest Java installed (you can use lab5 with this image `sonoma-java-24`)
Run Jenkins with `docker run --name jenkins-lts -p 8080:8080 -p 50000:50000 jenkins/jenkins:lts` (note the initial password is in the container logs)
1. Install the official version of the plugin
2. Configure a cloud. Ensure you select "Advanced -> No Delay Provisioning` to create more VMs.
3. Configure a build to use the generated template. Here is a sample one: 
```
pipeline {
agent none …
```
> OK-3786 Ensure no orphaned VMs

- src/main/java/io/jenkins/plugins/orka/AgentTemplate.java
- src/main/java/io/jenkins/plugins/orka/OrkaCloud.java
- src/main/java/io/jenkins/plugins/orka/client/DeploymentRequest.java
- src/main/java/io/jenkins/plugins/orka/client/OrkaClient.java
- src/main/java/io/jenkins/plugins/orka/helpers/FormValidator.java
- src/main/resources/io/jenkins/plugins/orka/AgentTemplate/config.jelly
- src/test/java/io/jenkins/plugins/orka/AgentTemplateTest.java
- src/test/java/io/jenkins/plugins/orka/GetTemplateTest.java
- src/test/java/io/jenkins/plugins/orka/client/OrkaClientTest.java
* [Cloud] Allow passing display settings to Orka
- Provide users with the ability to pass display settings to Orka
- Move rarely used VM settings to a separate "Advanced" section
- Add the display settings to this section
Follow the [dev guide](https://github.com/jenkinsci/macstadium-orka-plugin/tree/main/development) to install the plugin locally
1. Create a new Cloud
2. Create a new Agent template
3. Do not set display settings
4. Create a new job that spins up agents from the cloud above
5. Run the job and ensure VMs are created
6. Check the VM display settings (from the pod labels). They should be the default ones
1. Create a new Cloud
2. Create a new Agent template
3. Set display settings
4. Create a new job that spins up agents from the cloud above
5. Run the job and ensure VMs are …
> [Cloud] Allow passing display settings to VMs

- development/DEVELOPING.md
- src/main/java/io/jenkins/plugins/orka/OrkaAgent.java
- src/main/java/io/jenkins/plugins/orka/OrkaComputerLauncher.java
- src/main/resources/io/jenkins/plugins/orka/OrkaAgent/configure-entries.jelly
- Provide users with the ability to pass display settings to Orka
- Move rarely used VM settings to a separate "Advanced" section
- Add the display settings to this section
Follow the [dev guide](https://github.com/jenkinsci/macstadium-orka-plugin/tree/main/development) to install the plugin locally
1. Create a new Node using the Orka template
2. Do not set display settings
3. Check the VM display settings (from the pod labels). They should be the default ones
1. Create a new Node using the Orka template
2. Set
3. Check the VM display settings (from the pod labels). They should be the ones provided
> Add display settings to permanent agents
